name: bk_core
description: Core package
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=2.19.0 <3.0.0"
  flutter: 3.7.0

dependencies:
  flutter:
    sdk: flutter
  logger: ^2.3.0
  objectbox: ^4.0.1
  objectbox_flutter_libs: any
  provider: ^6.0.3
  timeago: ^3.2.2
  very_good_analysis: ^4.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  build_runner: ^2.3.3
  objectbox_generator: any

objectbox:
  output_dir: database